sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t egaribo/front-react -f Dockerfile.dev .

script:
  - docker run -e CI=true egaribo/front-react npm run test

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "dockerr"
#   env: "Dockerr-env"
#   bucket_name:
#   bucket_path:
#   on:
#     branch: master